name: Publish Python Package

on:
  release:
    types: [published]  # Изменено с created на published
  workflow_dispatch:    # Добавлена возможность ручного запуска

permissions:
  contents: read        # Необходимые permissions
  id-token: write       # Для OIDC аутентификации (если используете)

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine  # Используем modern build
    
    - name: Build package
      run: python -m build  # Современная альтернатива setup.py
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1  # Специальное действие для публикации
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}  # Или использует OIDC автоматически